return {
  -- Which-key
  Debugger = '',
  Run = '󰑮',
  Find = '',
  Session = '󱂬',
  Sort = '󰒺',
  Buffer = '󰓩',
  Terminal = '',
  UI = '',
  Test = '󰙨',
  Packages = '󰏖',
  Docs = '',
  Git = '󰊢',
  LSP = '',
  Menu = '',
  Window = '',

  -- Heirline-components - tabline
  BufferLineIndicator = '▎',
  BufferClose = '󰅖',
  FileModified = '',
  FileReadOnly = '',
  ArrowLeft = '',
  ArrowRight = '',
  TabClose = '󰅙',

  -- Heirline-components - winbar
  CompilerPlay = '',
  CompilerStop = '',
  CompilerRedo = '',
  NeoTree = '',
  Aerial = '',
  ZenMode = '󰰶',
  BufWrite = '',
  BufWriteAll = '',
  Ellipsis = '…',
  BreadcrumbSeparator = '',

  -- Heirline-components - statuscolumn
  FoldClosed = '',
  FoldOpened = '',
  FoldSeparator = ' ',

  -- Heirline-components - statusline
  ActiveLSP = '',
  ActiveTS = '',
  Environment = '',
  DiagnosticError = '',
  DiagnosticHint = '󰌵',
  DiagnosticInfo = '',
  DiagnosticWarn = '',
  LSPLoading1 = '',
  LSPLoading2 = '󰀚',
  LSPLoading3 = '',
  SearchCount = '',
  MacroRecording = '',
  ToggleResults = '󰑮',

  -- Heirline-components - misc
  Paste = '󰅌',
  PathSeparator = '',
  Indent = '│',
  LastIndent = '└',

  -- Neotree
  FolderClosed = '',
  FolderEmpty = '',
  FolderOpen = '',
  Diagnostic = '󰒡',
  DefaultFile = '󰈙',

  -- Languages icons
  Dotnet = '',
  Dart = '',
  Typescript = '',
  Javascript = '',
  HTML = '',
  CSS = '',
  Kotlin = '',
  Java = '',
  Python = '',
  Rust = '',
  Go = '',
  Lua = '',
  Help = '󰋖',

  -- Git
  GitBranch = '',
  GitAdd = '',
  GitChange = '',
  GitDelete = '',
  GitConflict = '',
  GitIgnored = '◌',
  GitRenamed = '➜',
  GitSign = '▎',
  GitStaged = '✓',
  GitUnstaged = '✗',
  GitUntracked = '★',

  -- DAP
  DapBreakpoint = '',
  DapBreakpointCondition = '',
  DapBreakpointRejected = '',
  DapLogPoint = '.>',
  DapStopped = '󰁕',

  -- Telescope
  PromptPrefix = '❯',

  -- Nvim-lightbulb
  Lightbulb = '💡',

  -- Mason
  MasonInstalled = '✓',
  MasonUninstalled = '✗',
  MasonPending = '⟳',

  -- Render-markdown
  RenderMarkdown = { ' ', ' ', '󰲥 ', '󰲧 ', '󰲩 ', '󰲫 ' },

  LSP_KINDS = {
    Array = ' ',
    Boolean = '󰨙 ',
    Class = ' ',
    Codeium = '󰘦 ',
    Color = ' ',
    Control = ' ',
    Collapsed = ' ',
    Constant = '󰏿 ',
    Constructor = ' ',
    Copilot = ' ',
    Enum = ' ',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = ' ',
    Folder = ' ',
    Function = '󰊕 ',
    Interface = ' ',
    Key = ' ',
    Keyword = ' ',
    Method = '󰊕 ',
    Module = ' ',
    Namespace = '󰦮 ',
    Null = ' ',
    Number = '󰎠 ',
    Object = ' ',
    Operator = ' ',
    Package = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = '󱄽 ',
    String = ' ',
    Struct = ' ',
    Supermaven = ' ',
    TabNine = '󰏚 ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = ' ',
    Value = ' ',
    Variable = ' ',
  },

  LSP_SERVERS_ICONS = {
    lua_language_server = '',
    vimls = '',
    pyright = '',
    tsserver = '',
    html = '',
    cssls = '',
    gopls = '',
    rust_analyzer = '',
    jdtls = '',
    kotlin_language_server = '',
    omnisharp = '',
    dartls = '',
    marksman = '',
    bashls = '',
    jsonls = 'ﬥ',
    yamlls = '',
    clangd = '󰌗',
    htmlcssls = '',
    cssmodules_ls = '',
    intelephense = '',
  },

  -- Others
  Vim = ' ',
  Lazy = '💤',
  Copilot = ' ',
}
