line_endings = "Unix"
quote_style = "AutoPreferSingle"

call_parentheses = "Always"
collapse_simple_statement = "Always"

indent_type = "Spaces"
indent_width = 2
column_width = 120
[sort_requires]
enabled = true
