return {}
-- return {
--   {
--     -- Make sure to set this up properly if you have lazy=true
--     'MeanderingProgrammer/render-markdown.nvim',
--     opts = {
--       file_types = { 'markdown', 'Avante' },
--     },
--     ft = { 'markdown', 'Avante' },
--   },
--   {
--
--     'iamcco/markdown-preview.nvim',
--     cmd = { 'MarkdownPreviewToggle', 'MarkdownPreview', 'MarkdownPreviewStop' },
--     build = 'cd app && yarn install',
--     init = function()
--       vim.g.mkdp_filetypes = { 'markdown' }
--     end,
--     ft = { 'markdown' },
--     keys = {
--       { '<leader>tmp', '<cmd>MarkdownPreviewToggle<cr>', desc = 'Toggle Markdown Preview' },
--     },
--     config = function()
--       vim.g.mkdp_auto_start = 0
--       vim.g.mkdp_auto_close = 1
--       vim.g.mkdp_refresh_slow = 0
--       vim.g.mkdp_command_for_global = 0
--       vim.g.mkdp_open_to_the_world = 0
--       vim.g.mkdp_browser = ''
--       vim.g.mkdp_echo_preview_url = 1
--       vim.g.mkdp_page_title = '${name}'
--     end,
--   },
-- }
