[[database]]
Name = "Production database"
Provider = "mysql"
DBName = "mozartnet"
URL = "Server=ftpinfotek.dnsalias.net;Database=mozartnet;uid=mozart;password=mozart123;"
ReadOnly = true

[[database]]
Name = "Development database"
Provider = "mysql"
DBName = "mozartnetdev"
URL = "Server=mozartdesarrollo.dnsalias.net;Database=mozartnetdev;uid=mozart;password=mozart123;"

[application]
DefaultPageSize = 300
DisableSidebar = false
SidebarOverlay = false
